### ISSUE TITLE
Tip Party Monetization Strategies

### ISSUE THREAD

**Issue by varunv5000** [moonshotcollective/tip.party#121]
### How do we monetize? :

**Current method: People have to pay for admin functionality in order to distribute tokens.**

- Pros: Could potentially generate a large amount of revenue if many people sign up as admin
- Cons: May make it tougher to onboard new customers. People may be unwilling to pay to use. Also, no new revenue after someone pays to be an admin.
- Revenue estimate:  Around $300 per admin signup assuming ETH = $3000. If 1,000 people sign up, then total revenue = $300,000. If 10,000: total revenue is $3,000,000

**Take a 2-3% cut of every Tip Party: Anyone can be an admin, but we take a cut of every tip party.**

- Pros: Much better onboarding since there is no paywall. Could generate lots of revenue if many DAOs are using it and large amounts of tokens are dropped through it.
- Cons: Taking a cut may be annoying to users dropping large amounts of money. Also, large amounts of money must be dropped through Tip Party to earn significant revenue.
- Revenue estimate: $1 mil volume ~ $30,000. $10 mil volume ~ $300,000

**DAOs must pay $10,000+ to list their token on Tip Party. Only listed tokens can be dropped through Tip Party.**

- Pros: Likely can generate the largest amount of revenue, especially if many DAOs pay to get their tokens listed.
- Cons: DAOs might be unwilling to pay a large amount to get their tokens listed
- Revenue estimate: 100 DAO tokens listed ~ $1 mil. 1000 DAO tokens listed ~ $10 mil

**No monetization: Tip Party is completely free for the public to use, and will be used to bolster the Gitcoin / Moonshot Collective brand and the other apps in the Gitcoin ecosystem**

- Pros: Easiest and simplest onboarding, people love stuff that is completely free to use!
- Cons: No revenue :(

**Varun's opinion: Go with the approach where DAOs must pay in order to list their token on Tip Party, since this would likely be the best way to earn revenue. This could also have the effect of providing legitimacy to any DAOs that have their tokens listed on Tip Party. If there is high demand, we could later on increase fees for DAOs trying to list their tokens.**

**We could additionally try to implement taking a cut of every Tip Party for additional revenue, but if the revenue would be too insignificant we should not implement this.**

**Comment by farque65** [comment]
Other possible monetization strategies
- Buying advertising on a tip.party room or homepage
- Rebranding a tip.party room. Where a DAO can request a reskin of a room they are using and we can charge for the designing.
