### ISSUE TITLE
Tip NFTs

### ISSUE THREAD

**Issue by wkarshat** [moonshotcollective/tip.party#151]
In addition to tipping with ETH or wETH or ERC20 tokens, one could tip with NFTs.

Though, unlike fungible tokens, where the tipper only needs to have a sufficient total balance, this many NFTs would have to be minted or pre-minted.
The UI or a dedicated contract could iterate over the mint and transfer for each account, fees and all. Recovering from an error mid-way the list of accounts could be tricky.

A simplifying assumption could be that the NFTs are "discrete", like Kudos or POAP, issued individually but the same otherwise. Perhaps the instance of the ERC721 contract should belong to the tipper.

Within the EVM limit on the maximum number of arguments [16], one could create a method to extend ERC721, to mint a batch of a dozen tokens, with the same URI but to different accounts.

**Comment by stevegachau** [comment]
@wkarshat @META-DREAMER would you like to collaborate on a few prototypes and see what works.
