### ISSUE TITLE
feature - integrate ta.cash

### ISSUE THREAD

**Issue by bobjiang** [moonshotcollective/tip.party#182]
Hi team,

I find a very interesting tool for sending/requesting tip named https://ta.cash/
which is built by AlphaWallet team.

As a tip sender/receiver, he could connect to twitter, and send tip to a twitter user.
So he doesn't need to know the receiver's address.

Ta.cash is live on Polygon, try it ;)

**Comment by codenamejason** [comment]
this is not the direction we are going.
