### ISSUE TITLE
Tip Party 2.0

### ISSUE THREAD

**Issue by varunv5000** [moonshotcollective/tip.party#188]
### Changes to smart contracts:

- Remove Tipsta contract / any distributor or admin roles
- Only keep splitEth, splitTokenFromUser, and _handleDistribution functions in the TokenDistributor contract
- Massive simplification of the smart contracts

### Home Page:

- Remove "Pay to be a distributor"
- Possibly remove "Wallet Not Connected" page to reduce user friction

### Room Page

- Users will be allowed to "Sign in as a Distributor" for each room
    - Only allowed if there are no distributors for the room already.
    - Will be done off-chain through signing in with wallet, and the distributor's address will be stored in the backend.
    - Once someone has signed in as a distributor for a room, then users can sign in as usual
    - Only one person can sign in as a distributor for a room
- Distributor Functions :
    - Add Address button: Allows the distributor to directly add addresses to the list
    - Clear button: Would immediately delete all addresses on the list
    - Distributors can permanently delete addresses on the list instead of sending to Blacklist
- Blacklist should be removed - it's a bit confusing, and it also gets reset if the user refreshes their browser'

### Design

- Tip Party could look a bit better. We could use a designer in the future!
- Make Tip Party mobile-optimized. Mobile wallets are the go-to for in-person events!

**Comment by farque65** [comment]
Some of these points are good. These do not need to be under one issue. These should be separated based on related bullet points.
