### ISSUE TITLE
L2 Support

### ISSUE THREAD

**Issue by farque65** [moonshotcollective/tip.party#204]
Deploy Contracts to Optimism, Arbitrum, Matic, Rinkeby, Mainnet

**Comment by brentmartin** [comment]
Networks already have up: XDAI, Matic, AVAX

Network integrations we would like to have: Optimism, Arbitrum

**Comment by brentmartin** [comment]
Priority right now is to have: XDAI, Matic, AVAX running

**Comment by varunv5000** [comment]
New contracts need to be updated to L2s still

**Comment by codenamejason** [comment]
Are we focusing on Optimism and Arbitrum for L2's?

**Comment by farque65** [comment]
Currently Deployed Networks:
- [x] Matic
- [x] Optimism
- [x] Rinkeby
- [ ] Arbitrum
- [ ] Mainnet
