### ISSUE TITLE
More info on transactions: add ENS + amount paid

### ISSUE THREAD

**Issue by varunv5000** [moonshotcollective/tip.party#255]
- The transaction history should give more information from the payout like the amount paid and ens of the user who paid

**Comment by varunv5000** [comment]
Should probably scrap this, I think the etherscan link gives all the info necessary, and additional info may be unnecessary

**Comment by farque65** [comment]
There will need to be larger changes to the transaction history section just based on usability testing. The user needs more info on the history at a glance of this tab. Especially hosts when they look through this days or months apart. This is definitely out of scope for the 217 launch. There are other more pressing issues to address.
