### ISSUE TITLE
Notification to Guest after Payout

### ISSUE THREAD

**Issue by codenamejason** [moonshotcollective/tip.party#271]
- [ ] Notification to guests after payout (does not disappear until user dismisses it)

**Comment by sameerthombrecareer** [comment]
Given a host tips a room and the guest is signed into the room, when the guest is looking at their screen, then the guest should see a persistent notification popup that says “You just got tipped {amount} {ERC20}” until the user closes the notification.

Given a host tips a room and the guest is signed into the room, when the guest is NOT looking at their screen in the moment but looks back at the room at a later point in time, then the guest should still see a persistent notification popup that says “You just got tipped {amount} {ERC20}” until the user closes the notification.
