### ISSUE TITLE
Token List does not work on staging (but it does work on my local environment)

### ISSUE THREAD

**Issue by varunv5000** [moonshotcollective/tip.party#284]

**Comment by farque65** [comment]
This does work for the networks there are valid token list urls. This token lists are available on mainnet, arbitrum and optimism. For every other network users will need to import addresses.

**Comment by varunv5000** [comment]
Still gives an issue for me. Does it work for you?

**Comment by varunv5000** [comment]
I tried on mainnet

**Comment by farque65** [comment]
> Still gives an issue for me. Does it work for you?

Yes it works

**Comment by farque65** [comment]
I do see a bug when "Import Token" is clicked on staging, the URL most likely needs to change
