### ISSUE TITLE
Copy Change: Signature Request Message

### ISSUE THREAD

**Issue by sameerthombrecareer** [moonshotcollective/tip.party#310]
**Context**
Given a guest signs into the room, a wallet modal (in my case, MetaMask) pops up prompting a Signature Request from the user with the room name as its Message.

**Updates (Actions)**
1. When the guest is signing into the room from their respective wallets…

We should update the sign message from “[insert room name]” to:

“This action will sign you in as a guest in the room [insert room name] in order to receive tips. This action does not cost tokens”

**Comment by farque65** [comment]
So the signature on guest signIn has to be the room name because the backend firebase function verifies the signIn message matches the room name before adding the user to a room in the firestore db. So we can't do a custom message
