### ISSUE TITLE
Adjust the size of blockies in tip.party guest list

### ISSUE THREAD

**Issue by farque65** [moonshotcollective/tip.party#354]
![Screen Shot 2022-02-28 at 10 24 26 AM](https://user-images.githubusercontent.com/8276680/156009580-4ca9ed74-6086-4183-b735-4f2bbd817051.png)

***Details***
- Address Blockie for each Guest list entry is too small and not inline with their respective address

***Steps to Reproduce Issue***
1) Join an existing room with multiple guests (for example coordination)
2) View the Guest list Blockies

***Acceptance Criteria***
- Blockie should be inline with address
- Blockie height should be almost the same as the guest list text font
- Navbar Current User Address Blockie should remain the same

**Comment by HenricoW** [comment]
Good day. I'm working on this

**Comment by HenricoW** [comment]
Hi. The above-mentioned PR fixes the bug for both the Guest and Host room lists, while maintaining the Address blockie's intended styling:

Guest room
![roomList_fixed](https://user-images.githubusercontent.com/29999494/156230669-be59b495-66ee-4904-93e3-37db9f0dceb4.PNG)

Host room
![hostLists_fixed](https://user-images.githubusercontent.com/29999494/156230702-187fde61-6b09-4acb-93f8-d2cc82ad6a88.PNG)

**Comment by farque65** [comment]
Awesome, will review
