### ISSUE TITLE
Create User groups for admins

### ISSUE THREAD

**Issue by farque65** [moonshotcollective/tip.party#45]
- First User group should be moonshot collective

**Comment by over9001** [comment]
For new users to use tip.party, it must be possible for them to 'sign up' and right now only existing admins can enroll new users. 
To make it possible to test with arbitrary external groups, we must add a ~'make me admin' feature.
Proposal:
New users may pay 0.1 eth (or 5GTC somehow? gas tho?) to become admin, and the balance (less contract and gas fees) is sent to moonshotcoordinator.eth 
(Is it possible to make it completely free and permissionless, and then add a permissioning and value regenerating (for MC and others) layer on top?)

**Comment by ghostffcode** [comment]
This feature has been implemented in the updated [Tip.Party](https://app.tip.party)
